description: Experimentos com Java e Quarkus framework no Backend 
name: java-quarkus-stackspot
display-name: Java Quarkus Playground
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility: # Put a list of technologies compatible with the stack
  - linux
  - windows
  - mac
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies 
  - java
  - quarkus
  - maven 
  - rest
about: docs/about.md
use-cases:
  - title: Vanilla
    content: docs/vanilla.md
    stackfile: stackfiles/vanilla.yaml